{START_FORM}

<p>{BASE_URI}{BASE_URI_LABEL}</p>
<p>{AUTH_URI}{AUTH_URI_LABEL}</p>
<p>{EMAIL_TEST_FLAG}{EMAIL_TEST_FLAG_LABEL}</p>
<p>{EXCEPTION_TEST_FLAG}{EXCEPTION_TEST_FLAG_LABEL}</p>
<p>{APC_TEST_FLAG}{APC_TEST_FLAG_LABEL}</p>
<p>{EMAIL_TEST_ADDRESS}{EMAIL_TEST_ADDRESS_LABEL}</p>
<p>{UBER_ADMIN_EMAIL}{UBER_ADMIN_EMAIL_LABEL}</p>
<p>{TRANSCRIPT_EMAIL}{TRANSCRIPT_EMAIL_LABEL}</p>
<p>{APPLICATION_EMAIL}{APPLICATION_EMAIL_LABEL}</p>
<p>{CURRENT_TERM}{CURRENT_TERM_LABEL}</p>
<p>{ADMINISTRATOR_AGREEMENT}{ADMINISTRATOR_AGREEMENT_LABEL}</p>
<p>{EXCEPTION_MESSAGE}{EXCEPTION_MESSAGE_LABEL}</p>
<p>{SUBMIT}</p>

{END_FORM}
